{
"version": 3,
"file": "Exception$Catch$.js",
"mappings": ";;;;;;AAyFQ,8CAAAA,SAAAA,CAAAA,2CAAAA,GAAAA;EAAuB,OAAAC,OAAAA,CAAAA,OAAAA,CAAAA,UAAAA,EAAvBA;E;AACA,8CAAAD,SAAAA,CAAAA,8CAAAA,GAAAA;EAAgC,WAAAC,OAAAA,CAAAA,CAAAA,CAAAA,mCAAAA,EAAAA,CAAAA,kCAAAA,CAAAA;qBAAAC,CAAAA;aAAAD,OAAAA,CAAAA,EAAAA,CAAAA,OAAAA,CAAAA,OAAAA,CAAAA,4BAAAA,EAAAA,CAAAA,sCAAAA,CAAAA,CAAAA,CAAAA,CAAAA;;OAAhC;E;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;AAHAA,OAAAA,CAAAA,eAAAA,CAAAA,kCAAAA,GAAAA,S;AAAAA,OAAAA,CAAAA,OAAAA,CAAAA,kCAAAA,GAAAA,YAAAA;QAAAA,OAAAA,CAAAA,eAAAA,CAAAA,kCAAAA,CAAAA;IAAAA,OAAAA,CAAAA,eAAAA,CAAAA,kCAAAA,GAAAA,IAAAA,OAAAA,CAAAA,CAAAA,CAAAA,mCAAAA,EAAAA,CAAAA,OAAAA,EAAAA;;SAAAA,OAAAA,CAAAA,eAAAA,CAAAA,kCAAAA;E;;",
"sources": ["file:///Users/tschlatt/Documents/scala-js/scalalib/fetchedSources/2.10.2/src/library/scala/util/control/Exception.scala"],
"names": ["prototype", "ScalaJS", "x"],
"lineCount": 56
}
