{
  "name": "scala.util.control.Exception$Catch$",
  "ancestorCount": 1,
  "isStaticModule": true,
  "isInterface": false,
  "isImplClass": false,
  "isRawJSType": false,
  "encodedName": "scala_util_control_Exception$Catch$",
  "superClass": "java_lang_Object",
  "ancestors": ["scala_util_control_Exception$Catch$", "java_lang_Object"],
  "isExported": false,
  "methods": {
    "__init__": {},
    "$$lessinit$greater$default$2__Lscala_Option": {
      "accessedModules": ["scala_None"]
    },
    "$$lessinit$greater$default$3__Lscala_Function1": {
      "calledMethods": {
        "scala_util_control_Exception$": ["shouldRethrow__Ljava_lang_Throwable__Z"],
        "scala_scalajs_runtime_AnonFunction1": ["init___Lscala_scalajs_js_Function1"]
      },
      "instantiatedClasses": ["scala_scalajs_runtime_AnonFunction1"],
      "accessedModules": ["scala_util_control_Exception"]
    },
    "init___": {
      "calledMethods": {
        "java_lang_Object": ["init___"]
      }
    }
  }
}
